language: ruby
script: bundle exec rake travis_spec
rvm:
  - 2.1.2
notifications:
  email:
    - carrickr@stanford.edu
    - pmangiafico@stanford.edu
    - laneymcg@stanford.edu
    - bess@stanford.edu
    