defaults: &defaults
  apo_field: "is_governed_by_s"
  collection_field: "is_member_of_collection_s"
  tag_field: "tag_facet"
  id_field: "id"
  collection_type: "collection"
  set_type: "set"
  apo_type: "adminpolicy"
  fedora_type_field: "identityMetadata_objectType_t" 
  druid_prefix: "druid:"
  last_changed: "published_dt"
  item_type: "item"
  fedora_prefix: "info:fedora/"
  title_field: "title_t"
  title_field_alt: "public_dc_title_t"
  
development:
  <<: *defaults
test: 
  <<: *defaults
staging: 
  <<: *defaults
production: 
  <<: *defaults